env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - 
    main: ./main.go
    binary: tag-nag
    ldflags:
      - -s -w 
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin 
    goarch:
      - amd64 
      - arm64 

archives:
  -
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc 
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'

release:
  draft: false
  prerelease: auto
