name: tag-nag

on:
  pull_request:
    branches: [main]

jobs:
  tag-nag:
    runs-on: ubuntu-latest
    
    container:
      image: jakebark/tag-nag:latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run terraform init # remove for CloudFormation
        run: |
          terraform init -backend=false
         
      - name: run tag-nag
        run: |
          tag-nag . --tags "tags"
