name: Release with GoReleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 
  # packages: write 

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
          cache: true 

      - name: run GoReleaser
        uses: goreleaser/goreleaser-action@v5 
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
