# .github/workflows/semgrep_scan.yml

name: semgrep

on:
  pull_request:
    branches: [ main ] 

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      contents: read          
      security-events: write 

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run semgrep
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep ci --sarif -o semgrep.sarif

      - name: sarif report
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif 
